#!/bin/bash

function try_rename() {
  if [ -z "$(tmux ls | grep ${SESSION_NAME})" ]; then
    tmux rename-session ${SESSION_NAME}
  else
    echo "Skipping session rename - ${SESSION_NAME} is already a tmux session"
  fi
}

if which tmux > /dev/null; then
  PROJECT=$(basename $(git rev-parse --show-toplevel))
  BRANCH=$(git rev-parse --abbrev-ref HEAD)
  SESSION_NAME="${PROJECT}/${BRANCH}";

  # Only rename if in tmux
  if [ ! -z ${TMUX_PANE} ]; then
    try_rename
  fi
fi

exit 0
